using MMZeroElements.Elements;
using Terraria.ID;
using Terraria.ModLoader;

namespace MMZeroElements.SetElements.Projectiles
{
    internal class FireProjectiles : GlobalProjectile
    {
        internal static int[] projectiles =
        {
            // Arrow
            ProjectileID.FireArrow,
            ProjectileID.JestersArrow,
            ProjectileID.HellfireArrow,
            ProjectileID.CursedArrow,
            // Bullet
            ProjectileID.MeteorShot,
            ProjectileID.CursedBullet,
            ProjectileID.ExplosiveBullet,
            // Rocket
            ProjectileID.RocketI,
            ProjectileID.RocketII,
            ProjectileID.RocketIII,
            ProjectileID.RocketIV,
            ProjectileID.ClusterRocketI,
            ProjectileID.ClusterRocketII,
            ProjectileID.DryRocket,
            ProjectileID.LavaRocket,
            ProjectileID.MiniNukeRocketI,
            ProjectileID.MiniNukeRocketII,
            ProjectileID.RocketSnowmanI,
            ProjectileID.RocketSnowmanII,
            ProjectileID.RocketSnowmanIII,
            ProjectileID.RocketSnowmanIV,
            ProjectileID.ClusterSnowmanRocketI,
            ProjectileID.ClusterSnowmanRocketII,
            ProjectileID.DrySnowmanRocket,
            ProjectileID.LavaSnowmanRocket,
            ProjectileID.MiniNukeSnowmanRocketI,
            ProjectileID.MiniNukeSnowmanRocketII,
            ProjectileID.GrenadeI,
            ProjectileID.GrenadeII,
            ProjectileID.GrenadeIII,
            ProjectileID.GrenadeIV,
            ProjectileID.ClusterGrenadeI,
            ProjectileID.ClusterGrenadeII,
            ProjectileID.DryGrenade,
            ProjectileID.LavaGrenade,
            ProjectileID.MiniNukeGrenadeI,
            ProjectileID.MiniNukeGrenadeII,
            ProjectileID.ProximityMineI,
            ProjectileID.ProximityMineII,
            ProjectileID.ProximityMineIII,
            ProjectileID.ProximityMineIV,
            ProjectileID.ClusterMineI,
            ProjectileID.ClusterMineII,
            ProjectileID.DryMine,
            ProjectileID.LavaMine,
            ProjectileID.MiniNukeMineI,
            ProjectileID.MiniNukeMineII,
            ProjectileID.RocketFireworkRed,
            ProjectileID.RocketFireworkGreen,
            ProjectileID.RocketFireworkBlue,
            ProjectileID.RocketFireworkYellow,
            ProjectileID.Celeb2Rocket,
            ProjectileID.Celeb2RocketExplosive,
            ProjectileID.Celeb2RocketLarge,
            ProjectileID.Celeb2RocketExplosiveLarge,
            // Flares
            ProjectileID.Flare,
            ProjectileID.BlueFlare,
            //ProjectileID.SpelunkerFlare,
            //ProjectileID.CursedFlare,
            //ProjectileID.RainbowFlare,
            //ProjectileID.ShimmerFlare,
            // Misc Ammo
            ProjectileID.CursedDart,
            ProjectileID.JackOLantern,
            ProjectileID.StarCannonStar,
            ProjectileID.EbonsandBallGun,

            // Accessory
            ProjectileID.StarCloakStar,

            // Melee
            //ProjectileID.BladeOfGrass,
            ProjectileID.Cascade,
            ProjectileID.Daybreak,
            ProjectileID.DaybreakExplosion,
            ProjectileID.EnchantedBoomerang,
            ProjectileID.EnchantedBeam,
            ProjectileID.Flamarang,
            ProjectileID.FlamingMace,
            ProjectileID.MonkStaffT2,
            ProjectileID.MonkStaffT2Ghast,
            ProjectileID.HelFire,
            ProjectileID.ShadowFlameKnife,
            ProjectileID.MonkStaffT3,
            ProjectileID.MonkStaffT3_Alt,
            ProjectileID.MonkStaffT3_AltShot,
            ProjectileID.SolarWhipSword,
            ProjectileID.SolarWhipSwordExplosion,
            ProjectileID.SolarFlareChainsaw,
            ProjectileID.SolarFlareDrill,
            ProjectileID.Sunfury,
            ProjectileID.Starfury,
            ProjectileID.StarWrath,
            //ProjectileID.Volcano,

            // Ranged
            ProjectileID.DD2BetsyArrow,
            ProjectileID.BoneGloveProj,
            ProjectileID.Flames,
            ProjectileID.Hellwing,
            ProjectileID.MolotovCocktail,
            ProjectileID.MolotovFire,
            ProjectileID.MolotovFire2,
            ProjectileID.MolotovFire3,
            ProjectileID.DD2PhoenixBow,
            ProjectileID.DD2PhoenixBowShot,
            ProjectileID.ShadowFlameArrow,
            ProjectileID.NailFriendly,

            // Magic
            ProjectileID.DD2BetsyFireball,
            ProjectileID.BookOfSkullsSkull,
            ProjectileID.ClingerStaff,
            ProjectileID.CursedFlameFriendly,
            ProjectileID.DemonScythe,
            ProjectileID.Flamelash,
            ProjectileID.BallofFire,
            ProjectileID.HeatRay,
            ProjectileID.InfernoFriendlyBolt,
            ProjectileID.InfernoFriendlyBlast,
            ProjectileID.LastPrism,
            ProjectileID.LastPrismLaser,
            ProjectileID.LunarFlare,
            ProjectileID.MagicMissile,
            ProjectileID.Meteor1,
            ProjectileID.Meteor2,
            ProjectileID.Meteor3,
            ProjectileID.NebulaBlaze1,
            ProjectileID.NebulaBlaze2,
            ProjectileID.FairyQueenMagicItemShot,
            ProjectileID.ShadowBeamFriendly,
            ProjectileID.ShadowFlame,
            ProjectileID.SpiritFlame,
            ProjectileID.UnholyTridentFriendly,
            ProjectileID.Spark,

            // Summon
            ProjectileID.ScytheWhip,
            ProjectileID.ScytheWhipProj,
            ProjectileID.DD2ExplosiveTrapT1,
            ProjectileID.DD2ExplosiveTrapT1Explosion,
            ProjectileID.DD2ExplosiveTrapT2,
            ProjectileID.DD2ExplosiveTrapT2Explosion,
            ProjectileID.DD2ExplosiveTrapT3,
            ProjectileID.DD2ExplosiveTrapT3Explosion,
            ProjectileID.FireWhip,
            ProjectileID.FireWhipProj,
            ProjectileID.DD2FlameBurstTowerT1,
            ProjectileID.DD2FlameBurstTowerT1Shot,
            ProjectileID.DD2FlameBurstTowerT2,
            ProjectileID.DD2FlameBurstTowerT2Shot,
            ProjectileID.DD2FlameBurstTowerT3,
            ProjectileID.DD2FlameBurstTowerT3Shot,
            ProjectileID.FlyingImp,
            ProjectileID.ImpFireball,
            ProjectileID.HoundiusShootius,
            ProjectileID.HoundiusShootiusFireball,
            ProjectileID.Spazmamini,
            ProjectileID.Retanimini,
            ProjectileID.MiniRetinaLaser,

            // NPC proj
            ProjectileID.Explosives,
            ProjectileID.CursedFlameHostile,
            ProjectileID.DemonSickle,
            ProjectileID.CursedFlameHostile,
            ProjectileID.ShadowBeamHostile,
            ProjectileID.UnholyTridentHostile,
            ProjectileID.RocketSkeleton,
            ProjectileID.HappyBomb,
            ProjectileID.EyeLaser,
            ProjectileID.EyeFire,
            ProjectileID.PinkLaser,
            ProjectileID.RuneBlast,
            ProjectileID.EbonsandBallFalling,
            ProjectileID.Fireball,
            ProjectileID.EyeBeam,
            ProjectileID.SeedPlantera,
            ProjectileID.PoisonSeedPlantera,
            ProjectileID.ThornBall,
            ProjectileID.InfernoHostileBlast,
            ProjectileID.InfernoHostileBolt,
            ProjectileID.Shadowflames,
            ProjectileID.GreekFire1,
            ProjectileID.GreekFire2,
            ProjectileID.GreekFire3,
            ProjectileID.FlamingScythe,
            ProjectileID.SaucerScrap,
            ProjectileID.CultistBossFireBall,
            ProjectileID.CultistBossFireBallClone,
            ProjectileID.Nail,
            ProjectileID.DesertDjinnCurse,
            ProjectileID.GeyserTrap,
            ProjectileID.DD2BetsyFlameBreath,
            ProjectileID.RollingCactus,
            ProjectileID.RollingCactusSpike,
        };

        public override void Load()
        {
            ProjectileElements.Fire.AddRange(projectiles);
        }

        public override void Unload()
        {
            ProjectileElements.Fire.Clear();
        }
    }
}
